version: '3.8'

services:
  app:
    container_name: springboot-postgresql
    image: springboot-app
    build: ./
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb

  postgresqldb:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data/pgdata
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres